//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Collections.Generic;
using NHibernate.Envers.Tests.Entities;
using NUnit.Framework;

namespace NHibernate.Envers.Tests.Integration.RevEntity
{
	using System.Threading.Tasks;
	public partial class ExceptionListenerTest : TestBase
	{

		[Test]
		public async Task EntityShouldNotHaveBeenPersistedAsync()
		{
			Assert.AreEqual(0, await (Session.CreateQuery("select count(s) from StrTestEntity s where s.Str='x'").UniqueResultAsync()).ConfigureAwait(false));
		}
	}
}