//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System.Collections.Generic;
using NHibernate.Cfg;
using NHibernate.Envers.Configuration;
using NUnit.Framework;
using SharpTestsEx;

namespace NHibernate.Envers.Tests.Integration.Collection.NoRevision
{
	using System.Threading.Tasks;
	public abstract partial class AbstractCollectionChangeTest : TestBase
	{

		[Test]
		public async Task VerifyPersonRevisionCountAsync() 
		{
			(await (AuditReader().GetRevisionsAsync(typeof(Person),PersonId)).ConfigureAwait(false))
				.Should().Have.SameSequenceAs(ExpectedPersonRevisions);
		}
	}
}