//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using NHibernate.Dialect;
using NUnit.Framework;

namespace NHibernate.Envers.Tests.NetSpecific.Integration.CustomType
{
	using System.Threading.Tasks;
	public partial class CLOBCustomTest : TestBase
	{


		[Test]
		public async Task VerifyRevisionCountAsync()
		{
			CollectionAssert.AreEquivalent(new[] { 1, 2, 3 }, await (AuditReader().GetRevisionsAsync(typeof(CLOBCustomTypeEntity), ccte_id)).ConfigureAwait(false));
		}

		[Test]
		public async Task VerifyHistoryOfCcteAsync()
		{
			var rev1 = await (AuditReader().FindAsync<CLOBCustomTypeEntity>(ccte_id, 1)).ConfigureAwait(false);
			var rev2 = await (AuditReader().FindAsync<CLOBCustomTypeEntity>(ccte_id, 2)).ConfigureAwait(false);

			Assert.AreEqual("U", rev1.Str);
			Assert.AreEqual("V", rev2.Str);
		}

		[Test]
		public async Task VerifyLengthOfCcteAsync()
		{
			var rev3 = await (AuditReader().FindAsync<CLOBCustomTypeEntity>(ccte_id, 3)).ConfigureAwait(false);

			Assert.AreEqual(20000, rev3.Str.Length);
		}
	}
}