//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System.Collections.Generic;
using NHibernate.Envers.Tests.Integration.Interfaces.Inheritance.PropertiesAudited;
using NUnit.Framework;
using SharpTestsEx;

namespace NHibernate.Envers.Tests.NetSpecific.Integration.Configuration
{
	using System.Threading.Tasks;
	public partial class SchemaForAbstractUnionSubclassTest : TestBase
	{

		[Test]
		public async Task ShouldBeAbleToQueryBaseTypeAsync()
		{
			(await (AuditReader().FindAsync<ISimple>(id, 1)).ConfigureAwait(false))
				.Should().Not.Be.Null();
		}
	}
}