//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System.Collections.Generic;
using NHibernate.Envers.Query.Criteria;
using NHibernate.Envers.Query.Order;
using NHibernate.SqlCommand;

namespace NHibernate.Envers.Query
{
	using System.Threading.Tasks;
	using System.Threading;
	public partial interface IEntityAuditQuery<T> where T: class
	{
		Task<IEnumerable<T>> ResultsAsync(CancellationToken cancellationToken = default(CancellationToken));
		Task<T> SingleAsync(CancellationToken cancellationToken = default(CancellationToken));
	}
}