//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System.Collections;
using NHibernate.Envers.Query;
using NUnit.Framework;
using SharpTestsEx;

namespace NHibernate.Envers.Tests.NetSpecific.Integration.Access.Readonly
{
	using System.Threading.Tasks;
	public partial class ReadonlyAccessTest : TestBase
	{

		[Test]
		public async Task VerifyRevisionCountsAsync()
		{
			CollectionAssert.AreEqual(new[] { 1, 2 }, await (AuditReader().GetRevisionsAsync(typeof(ReadonlyEntity), id)).ConfigureAwait(false));
		}

		[Test]
		public async Task VerifyHistoryOfComponentAsync()
		{
			var ver1 = await (AuditReader().FindAsync<ReadonlyEntity>(id, 1)).ConfigureAwait(false);
			var ver2 = await (AuditReader().FindAsync<ReadonlyEntity>(id, 2)).ConfigureAwait(false);

			ver1.Data.Should().Be.EqualTo(1);
			ver1.ReadonlyData.Should().Be.EqualTo(0);

			ver2.Data.Should().Be.EqualTo(2);
			ver2.ReadonlyData.Should().Be.EqualTo(0);
		}

		[Test]
		public async Task CanQueryOnReadonlyDataAsync()
		{
			var res = (IList)await (AuditReader().CreateQuery()
				.ForRevisionsOfEntity(typeof (ReadonlyEntity), false, false)
				.Add(AuditEntity.Property("ReadonlyData").Eq(2))
				.GetSingleResultAsync()).ConfigureAwait(false);

			var ent = (ReadonlyEntity) res[0];
			var rev = (DefaultRevisionEntity) res[1];

			rev.Id.Should().Be.EqualTo(2);
			ent.Data.Should().Be.EqualTo(2);
			ent.ReadonlyData.Should().Be.EqualTo(0);
		}
	}
}