//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Collections;
using System.Collections.Generic;
using NHibernate.Collection;
using NHibernate.Engine;
using NHibernate.Envers.Configuration;
using NHibernate.Envers.Reader;
using NHibernate.Envers.Tools;
using NHibernate.Envers.Tools.Reflection;

namespace NHibernate.Envers.Entities.Mapper.Relation
{
	using System.Threading.Tasks;
	using System.Threading;
	public abstract partial class AbstractToOneMapper : IPropertyMapper
	{


		protected abstract Task NullSafeMapToEntityFromMapAsync(AuditConfiguration verCfg, object obj, IDictionary data,
		                                                   object primaryKey, IAuditReaderImplementor versionsReader, long revision, CancellationToken cancellationToken = default(CancellationToken));
	}
}