//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using NHibernate.Envers.Tests.Integration.Inheritance.Entities;
using NUnit.Framework;

namespace NHibernate.Envers.Tests.Integration.Inheritance.Joined.EmptyChild
{
	using System.Threading.Tasks;
	public partial class EmptyChildAuditingTest : TestBase
	{

		[Test]
		public async Task VerifyRevisionCountAsync()
		{
			CollectionAssert.AreEquivalent(new[] { 1, 2 }, await (AuditReader().GetRevisionsAsync(typeof(EmptyChildEntity), id1)).ConfigureAwait(false));
		}

		[Test]
		public async Task VerifyHistoryOfChildId1Async()
		{
			var ver1 = new EmptyChildEntity { Id = id1, Data = "x" };
			var ver2 = new EmptyChildEntity { Id = id1, Data = "y" };

			Assert.AreEqual(ver1, await (AuditReader().FindAsync<EmptyChildEntity>(id1, 1)).ConfigureAwait(false));
			Assert.AreEqual(ver2, await (AuditReader().FindAsync<EmptyChildEntity>(id1, 2)).ConfigureAwait(false));
		}

		[Test]
		public async Task VerifyPolymorphicQueryAsync()
		{
			var childVer1 = new EmptyChildEntity { Id = id1, Data = "x" };

			Assert.AreEqual(childVer1, await (AuditReader().CreateQuery().ForEntitiesAtRevision(typeof(EmptyChildEntity), 1).GetSingleResultAsync()).ConfigureAwait(false));
			Assert.AreEqual(childVer1, await (AuditReader().CreateQuery().ForEntitiesAtRevision(typeof(ParentEntity), 1).GetSingleResultAsync()).ConfigureAwait(false));
		}
	}
}