//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System.Collections.Generic;
using NHibernate.Envers.Tests.Entities.OneToOne;
using NUnit.Framework;
using SharpTestsEx;

namespace NHibernate.Envers.Tests.Integration.OneToOne.BiDirectional
{
	using System.Threading.Tasks;
	public partial class BidirectionalEagerHbmTest : TestBase
	{

		[Test]
		public async Task VerifyNonProxyObjectTraversingAsync()
		{
			var referencing = await (AuditReader().FindAsync<BidirectionalEagerHbmRefIngPK>(refIngId1, 1)).ConfigureAwait(false);
			referencing.Reference.Data.Should().Not.Be.Null();
		}
	}
}