//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using NUnit.Framework;
using SharpTestsEx;

namespace NHibernate.Envers.Tests.Integration.EntityNames.SingleAssociatedAudited
{
	using System.Threading.Tasks;
	public partial class SingleDomainObjectToMultipleTablesTest : TestBase
	{

		[Test]
		public async Task VerifySingleDomainObjectToMultipleTablesMappingAsync()
		{
			var carVer1 = await (AuditReader().FindAsync<Car>(carId, 1)).ConfigureAwait(false);
			var ownerVer1 = (Person)await (AuditReader().FindAsync("Personaje", ownerId, 1)).ConfigureAwait(false);
			var driverVer1 = (Person)await (AuditReader().FindAsync("Driveraje", driverId, 1)).ConfigureAwait(false);

			carVer1.Owner.Id.Should().Be.EqualTo(ownerVer1.Id);
			carVer1.Driver.Id.Should().Be.EqualTo(driverVer1.Id);

			ownerVer1.Name.Should().Be.EqualTo("Lukasz");
			driverVer1.Name.Should().Be.EqualTo("Kinga");
			carVer1.Number.Should().Be.EqualTo(1);
		}
	}
}