//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System.Collections.Generic;
using System.IO;
using System.Runtime.Serialization.Formatters.Binary;
using NHibernate.Envers.Tests.Entities.OneToMany;
using NUnit.Framework;

namespace NHibernate.Envers.Tests.Integration.Serialization
{
	using System.Threading.Tasks;
	public partial class SerializingCollectionTest : TestBase
	{

		[Test]
		public async Task VerifyDetachedAsync()
		{
			var ing1 = await (Session.GetAsync<CollectionRefIngEntity>(ing1_id)).ConfigureAwait(false);
			var rev1 = await (AuditReader().FindAsync<CollectionRefEdEntity>(ed1_id, 1)).ConfigureAwait(false);

			// First forcing loading of the collection
			Assert.AreEqual(1, rev1.Reffering.Count);

			// Now serializing and de-serializing the object
			rev1 = serializeObject(rev1);

			// And checking the collection again
			CollectionAssert.AreEqual(new[]{ing1}, rev1.Reffering);
		}
	}
}