//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using NUnit.Framework;
using SharpTestsEx;

namespace NHibernate.Envers.Tests.NetSpecific.Integration.PropertyNull
{
	using System.Threading.Tasks;
	public partial class PrimitiveNullTest : TestBase
	{

		[Test]
		public async Task ShouldBeAbleToFindAuditedEntityAsync()
		{
			var rev = await (AuditReader().FindAsync<EntityWithPrimitiveNullAsCamelcaseUnderscore>(id, 1)).ConfigureAwait(false);
			rev.Id.Should().Be.EqualTo(id);
			rev.Value.Should().Be.EqualTo(1);
		}
	}
}