//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Collections.Generic;
using System.Linq;
using NHibernate.Envers.Tests.Entities;
using NUnit.Framework;
using SharpTestsEx;

namespace NHibernate.Envers.Tests.NetSpecific.Integration.RevInfo.Time
{
	using System.Threading.Tasks;
	public partial class DateTimeTest : TestBase
	{

		[Test]
		public async Task ShouldUseUtcDateForRevisionDateAsync()
		{
			var utcNow = DateTime.UtcNow;
			var res = (await (AuditReader().CreateQuery().ForHistoryOf<StrTestEntity, DefaultRevisionEntity>().ResultsAsync()).ConfigureAwait(false)).First();
			res.RevisionEntity.RevisionDate.Should().Be.IncludedIn(utcNow.AddMinutes(-1), utcNow.AddMinutes(1));
		}
	}
}