//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System.Collections.Generic;
using System.Linq;
using NUnit.Framework;

namespace NHibernate.Envers.Tests.NetSpecific.Integration.BidirectionalSameColumn
{
	using System.Threading.Tasks;
	public partial class TwoRelationEndsSameColumnTest : TestBase
	{


		[Test]
		public async Task ShouldAuditModelProperlyAsync()
		{
			var modelFromAudit = await (Session.Auditer().CreateQuery()
										.ForRevisionsOf<Model>().SingleAsync()).ConfigureAwait(false);

			Assert.AreEqual(modelId, modelFromAudit.Id);
			Assert.AreEqual(modelConfigurationId, modelFromAudit.ModelConfigurations.Single().Id);
			Assert.AreEqual(modelId, modelFromAudit.ModelConfigurations.Single().Model.Id);
		}
	}
}
