//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System.Collections.Generic;
using NHibernate.Envers.Tests.Entities.ManyToMany;
using NUnit.Framework;

namespace NHibernate.Envers.Tests.Integration.ManyToMany
{
	using System.Threading.Tasks;
	public partial class BasicSetTest : TestBase
	{

		[Test]
		public async Task VerifyRevisionCountAsync()
		{
			CollectionAssert.AreEquivalent(new[] { 1, 2, 4 }, await (AuditReader().GetRevisionsAsync(typeof(SetOwnedEntity), ed1_id)).ConfigureAwait(false));
			CollectionAssert.AreEquivalent(new[] { 1, 2, 3, 5 }, await (AuditReader().GetRevisionsAsync(typeof(SetOwnedEntity), ed2_id)).ConfigureAwait(false));
			CollectionAssert.AreEquivalent(new[] { 1, 2, 3, 4, 5 }, await (AuditReader().GetRevisionsAsync(typeof(SetOwningEntity), ing1_id)).ConfigureAwait(false));
			CollectionAssert.AreEquivalent(new[] { 1, 2 }, await (AuditReader().GetRevisionsAsync(typeof(SetOwningEntity), ing2_id)).ConfigureAwait(false));
		}

		[Test]
		public async Task VerifyHistoryOfEd1Async()
		{
			var ing1 = await (Session.GetAsync<SetOwningEntity>(ing1_id)).ConfigureAwait(false);
			var ing2 = await (Session.GetAsync<SetOwningEntity>(ing2_id)).ConfigureAwait(false);

			var rev1 = await (AuditReader().FindAsync<SetOwnedEntity>(ed1_id, 1)).ConfigureAwait(false);
			var rev2 = await (AuditReader().FindAsync<SetOwnedEntity>(ed1_id, 2)).ConfigureAwait(false);
			var rev3 = await (AuditReader().FindAsync<SetOwnedEntity>(ed1_id, 3)).ConfigureAwait(false);
			var rev4 = await (AuditReader().FindAsync<SetOwnedEntity>(ed1_id, 4)).ConfigureAwait(false);
			var rev5 = await (AuditReader().FindAsync<SetOwnedEntity>(ed1_id, 5)).ConfigureAwait(false);

			CollectionAssert.IsEmpty(rev1.Referencing);
			CollectionAssert.AreEquivalent(new[] { ing1, ing2 }, rev2.Referencing);
			CollectionAssert.AreEquivalent(new[] { ing1, ing2 }, rev3.Referencing);
			CollectionAssert.AreEquivalent(new[] { ing2 }, rev4.Referencing);
			CollectionAssert.AreEquivalent(new[] { ing2 }, rev5.Referencing);
		}

		[Test]
		public async Task VerifyHistoryOfEd2Async()
		{
			var ing1 = await (Session.GetAsync<SetOwningEntity>(ing1_id)).ConfigureAwait(false);
			var ing2 = await (Session.GetAsync<SetOwningEntity>(ing2_id)).ConfigureAwait(false);

			var rev1 = await (AuditReader().FindAsync<SetOwnedEntity>(ed2_id, 1)).ConfigureAwait(false);
			var rev2 = await (AuditReader().FindAsync<SetOwnedEntity>(ed2_id, 2)).ConfigureAwait(false);
			var rev3 = await (AuditReader().FindAsync<SetOwnedEntity>(ed2_id, 3)).ConfigureAwait(false);
			var rev4 = await (AuditReader().FindAsync<SetOwnedEntity>(ed2_id, 4)).ConfigureAwait(false);
			var rev5 = await (AuditReader().FindAsync<SetOwnedEntity>(ed2_id, 5)).ConfigureAwait(false);

			CollectionAssert.IsEmpty(rev1.Referencing);
			CollectionAssert.AreEquivalent(new[] { ing2 }, rev2.Referencing);
			CollectionAssert.AreEquivalent(new[] { ing1, ing2 }, rev3.Referencing);
			CollectionAssert.AreEquivalent(new[] { ing1, ing2 }, rev4.Referencing);
			CollectionAssert.AreEquivalent(new[] { ing2 }, rev5.Referencing);
		}

		[Test]
		public async Task VerifyHistoryIng1Async()
		{
			var ed1 = await (Session.GetAsync<SetOwnedEntity>(ed1_id)).ConfigureAwait(false);
			var ed2 = await (Session.GetAsync<SetOwnedEntity>(ed2_id)).ConfigureAwait(false);

			var rev1 = await (AuditReader().FindAsync<SetOwningEntity>(ing1_id, 1)).ConfigureAwait(false);
			var rev2 = await (AuditReader().FindAsync<SetOwningEntity>(ing1_id, 2)).ConfigureAwait(false);
			var rev3 = await (AuditReader().FindAsync<SetOwningEntity>(ing1_id, 3)).ConfigureAwait(false);
			var rev4 = await (AuditReader().FindAsync<SetOwningEntity>(ing1_id, 4)).ConfigureAwait(false);
			var rev5 = await (AuditReader().FindAsync<SetOwningEntity>(ing1_id, 5)).ConfigureAwait(false);

			CollectionAssert.IsEmpty(rev1.References);
			CollectionAssert.AreEquivalent(new[] { ed1 }, rev2.References);
			CollectionAssert.AreEquivalent(new[] { ed1, ed2 }, rev3.References);
			CollectionAssert.AreEquivalent(new[] { ed2 }, rev4.References);
			CollectionAssert.IsEmpty(rev5.References);
		}

		[Test]
		public async Task VerifyHistoryIng2Async()
		{
			var ed1 = await (Session.GetAsync<SetOwnedEntity>(ed1_id)).ConfigureAwait(false);
			var ed2 = await (Session.GetAsync<SetOwnedEntity>(ed2_id)).ConfigureAwait(false);

			var rev1 = await (AuditReader().FindAsync<SetOwningEntity>(ing2_id, 1)).ConfigureAwait(false);
			var rev2 = await (AuditReader().FindAsync<SetOwningEntity>(ing2_id, 2)).ConfigureAwait(false);
			var rev3 = await (AuditReader().FindAsync<SetOwningEntity>(ing2_id, 3)).ConfigureAwait(false);
			var rev4 = await (AuditReader().FindAsync<SetOwningEntity>(ing2_id, 4)).ConfigureAwait(false);
			var rev5 = await (AuditReader().FindAsync<SetOwningEntity>(ing2_id, 5)).ConfigureAwait(false);

			CollectionAssert.IsEmpty(rev1.References);
			CollectionAssert.AreEquivalent(new[] { ed1, ed2 }, rev2.References);
			CollectionAssert.AreEquivalent(new[] { ed1, ed2 }, rev3.References);
			CollectionAssert.AreEquivalent(new[] { ed1, ed2 }, rev4.References);
			CollectionAssert.AreEquivalent(new[] { ed1, ed2 }, rev5.References);
		}
	}
}