//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System.Collections.Generic;
using NHibernate.Envers.Tests.Entities.CustomType;
using NUnit.Framework;

namespace NHibernate.Envers.Tests.Integration.CustomType
{
	using System.Threading.Tasks;
	public partial class ParametrizedCustomTest : TestBase
	{

		[Test]
		public async Task VerifyRevisionCountAsync()
		{
			CollectionAssert.AreEquivalent(new[] { 1, 2 }, await (AuditReader().GetRevisionsAsync(typeof(ParametrizedCustomTypeEntity), pcte_id)).ConfigureAwait(false));
		}

		[Test]
		public async Task VerifyHistoryOfPcteAsync()
		{
			var rev1 = await (AuditReader().FindAsync<ParametrizedCustomTypeEntity>(pcte_id, 1)).ConfigureAwait(false);
			var rev2 = await (AuditReader().FindAsync<ParametrizedCustomTypeEntity>(pcte_id, 2)).ConfigureAwait(false);

			Assert.AreEqual("xUy", rev1.Str);
			Assert.AreEqual("xVy", rev2.Str);
		}
	}
}