//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System.Collections.Generic;
using NHibernate.Envers.Tests.Entities.CustomType;
using NUnit.Framework;

namespace NHibernate.Envers.Tests.Integration.CustomType
{
	using System.Threading.Tasks;
	public partial class PrimitiveCustomTest : TestBase
	{

		[Test]
		public async Task VerifyRevisionCountAsync()
		{
			CollectionAssert.AreEquivalent(new[] { 1, 2 }, await (AuditReader().GetRevisionsAsync(typeof(PrimitiveCustomTypeEntity), pctec_id)).ConfigureAwait(false));
		}

		[Test]
		public async Task VerifyHistoryOfPctecAsync()
		{
			var rev1 = await (AuditReader().FindAsync<PrimitiveCustomTypeEntity>(pctec_id, 1)).ConfigureAwait(false);
			var rev2 = await (AuditReader().FindAsync<PrimitiveCustomTypeEntity>(pctec_id, 2)).ConfigureAwait(false);

			Assert.AreEqual('u', rev1.PrimitiveType.CharValue);
			Assert.AreEqual('v', rev2.PrimitiveType.CharValue);
		}
	}
}
