//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using NUnit.Framework;
using SharpTestsEx;

namespace NHibernate.Envers.Tests.NetSpecific.Integration.DynamicComponent
{
	using System.Threading.Tasks;
	public partial class MultiplePropertyTest : TestBase
	{

		[Test]
		public async Task VerifyRevisionCountAsync()
		{
			(await (AuditReader().GetRevisionsAsync(typeof(DynamicTestEntity), id)).ConfigureAwait(false))
				.Should().Have.SameSequenceAs(1, 2);
		}

		[Test]
		public async Task VerifyRevision1Async()
		{
			var rev = await (AuditReader().FindAsync<DynamicTestEntity>(id, 1)).ConfigureAwait(false);

			rev.Properties["Prop1"].Should().Be.EqualTo(1);
			rev.Properties["Prop2"].Should().Be.EqualTo(2);
			rev.Properties["Prop3"].Should().Be.EqualTo(3);
		}

		[Test]
		public async Task VerifyRevision2Async()
		{
			var rev = await (AuditReader().FindAsync<DynamicTestEntity>(id, 2)).ConfigureAwait(false);

			rev.Properties["Prop1"].Should().Be.EqualTo(1);
			rev.Properties["Prop2"].Should().Be.EqualTo(2);
			rev.Properties["Prop3"].Should().Be.EqualTo(33);
		}
	}
}