//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System.Collections.Generic;
using System.Linq;
using NHibernate.Cfg;
using NHibernate.Envers.Configuration;
using NHibernate.Envers.Query;
using NHibernate.Envers.Tests.Entities.Collection;
using NUnit.Framework;
using SharpTestsEx;

namespace NHibernate.Envers.Tests.NetSpecific.Integration.Proxy
{
	using System.Threading.Tasks;
	public partial class StringCollectionRemovedObjectQueryTest : TestBase
	{

		[Test]
		public async Task VerifyHistoryOfParentAsync()
		{
			(await (AuditReader().FindAsync<StringSetEntity>(parentId, 1)).ConfigureAwait(false))
						 .Strings.Should().Be.Empty();
			(await (AuditReader().FindAsync<StringSetEntity>(parentId, 2)).ConfigureAwait(false))
						 .Strings.Single().Should().Be.EqualTo("2");
			var rev3 = await (AuditReader().CreateQuery().ForRevisionsOfEntity(typeof(StringSetEntity), true, true)
									 .Add(AuditEntity.Id().Eq(parentId))
									 .Add(AuditEntity.RevisionNumber().Eq(3))
									 .GetSingleResultAsync<StringSetEntity>()).ConfigureAwait(false);
			rev3.Strings.Single().Should().Be.EqualTo("2");
		}
	}
}