using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace NHibernate.Envers
{
    /**
     * @author Simon Duduica, port of Envers omonyme class by Adam Warski (adam at warski dot org)
     */
    [AttributeUsage(AttributeTargets.Property | AttributeTargets.Method | AttributeTargets.Field)]
    class ColumnAttribute :Attribute
    {
        /**
         * The name of the column. Defaults to the property or field name
         */
        public String name = "";
        /**
         * Whether the property is a unique key. This is a shortcut for the UniqueConstraint
         * annotation at the table level and is useful for when the unique key constraint is
         * only a single field. This constraint applies in addition to any constraint entailed
         * by primary key mapping and to constraints specified at the table level.
         */
        public bool unique = false;
        /**
         * Whether the database column is nullable
         */
        public bool nullable = true;
        /**
         * Whether the column is included in SQL INSERT statements generated by the persistence provider.
         */
        public bool insertable = true;
        /**
         * Whether the column is included in SQL UPDATE statements generated by the persistence provider.
         */
        public bool updatable = true;
        /**
         * The SQL fragment that is used when generating the DDL for the column.
         * Defaults to the generated SQL to create a column of the inferred type.
         */
        public String columnDefinition = "";
        /**
         * The name of the table that contains the column. If absent the column is assumed to
         * be in the primary table.
         */
        public String table = "";
        /**
         * The column length. (Applies only if a string-valued column is used.)
         */
        public int length = 255;
        /**
         * The precision for a decimal (exact numeric) column. (Applies only if a decimal column is used.)
         * Value must be set by developer if used when generating the DDL for the column.
         */
        public int precision = 0;
        /**
         * The scale for a decimal (exact numeric) column. (Applies only if a decimal column is used.)
         */
        public int scale = 0;
    }
}
