//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System.Collections.Generic;
using NHibernate.Envers.Tests.Entities.Ids;
using NUnit.Framework;
using SharpTestsEx;

namespace NHibernate.Envers.Tests.Integration.OneToOne.UniDirectional
{
	using System.Threading.Tasks;
	public partial class UnidirectionalMulIdWithNullsTest : TestBase
	{

		[Test]
		public async Task VerifyNullReferenceAsync()
		{
			(await (AuditReader().FindAsync<UniRefIngMulIdEntity>(2, 1)).ConfigureAwait(false)).Reference
				.Should().Be.Null();
		}

		[Test]
		public async Task VerifyNotNullReferenceAsync()
		{
			(await (AuditReader().FindAsync<UniRefIngMulIdEntity>(1, 1)).ConfigureAwait(false)).Reference.Str1
				.Should().Be.EqualTo("data");
		}
	}
}