//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System.Collections.Generic;
using NHibernate.Envers.Tests.Entities;
using NHibernate.Envers.Tests.Entities.ManyToOne.UniDirectional;
using NHibernate.Proxy;
using NUnit.Framework;

namespace NHibernate.Envers.Tests.Integration.ManyToOne.UniDirectional
{
	using System.Threading.Tasks;
	public partial class RelationNotAuditedTargetTest : TestBase
	{

		[Test]
		public async Task VerifyRevisionCountAsync()
		{
			CollectionAssert.AreEquivalent(new[] { 1, 2, 4 }, await (AuditReader().GetRevisionsAsync(typeof(TargetNotAuditedEntity), tnae1_id)).ConfigureAwait(false));
			CollectionAssert.AreEquivalent(new[] { 1, 2, 3, 4 }, await (AuditReader().GetRevisionsAsync(typeof(TargetNotAuditedEntity), tnae2_id)).ConfigureAwait(false));
		}

		[Test]
		public async Task VerifyHistoryNae1Async()
		{
			// load original "tnae1" TargetNotAuditedEntity to force load "str1" UnversionedStrTestEntity as Proxy
			var original = await (Session.GetAsync<TargetNotAuditedEntity>(tnae1_id)).ConfigureAwait(false);

			var uste1 = await (Session.GetAsync<UnversionedStrTestEntity>(uste1_id)).ConfigureAwait(false);
			var uste2 = await (Session.GetAsync<UnversionedStrTestEntity>(uste2_id)).ConfigureAwait(false);

			var rev1 = await (AuditReader().FindAsync<TargetNotAuditedEntity>(tnae1_id, 1)).ConfigureAwait(false);
			var rev2 = await (AuditReader().FindAsync<TargetNotAuditedEntity>(tnae1_id, 2)).ConfigureAwait(false);
			var rev3 = await (AuditReader().FindAsync<TargetNotAuditedEntity>(tnae1_id, 3)).ConfigureAwait(false);
			var rev4 = await (AuditReader().FindAsync<TargetNotAuditedEntity>(tnae1_id, 4)).ConfigureAwait(false);

			Assert.AreEqual(uste1, rev1.Reference);
			Assert.AreEqual(uste2, rev2.Reference);
			Assert.AreEqual(uste2, rev3.Reference);
			Assert.AreEqual(uste1, rev4.Reference);

			Assert.IsTrue(original.Reference is INHibernateProxy);
			Assert.AreEqual(typeof(UnversionedStrTestEntity), await (NHibernateUtil.GetClassAsync(original.Reference)).ConfigureAwait(false));
			Assert.AreEqual(typeof(UnversionedStrTestEntity), NHibernateProxyHelper.GetClassWithoutInitializingProxy(rev1.Reference));
			Assert.AreEqual(typeof(UnversionedStrTestEntity), await (NHibernateUtil.GetClassAsync(rev1.Reference)).ConfigureAwait(false));
		}

		[Test]
		public async Task VerifyHistoryNae2Async()
		{
			var uste1 = await (Session.GetAsync<UnversionedStrTestEntity>(uste1_id)).ConfigureAwait(false);
			var uste2 = await (Session.GetAsync<UnversionedStrTestEntity>(uste2_id)).ConfigureAwait(false);

			var rev1 = await (AuditReader().FindAsync<TargetNotAuditedEntity>(tnae2_id, 1)).ConfigureAwait(false);
			var rev2 = await (AuditReader().FindAsync<TargetNotAuditedEntity>(tnae2_id, 2)).ConfigureAwait(false);
			var rev3 = await (AuditReader().FindAsync<TargetNotAuditedEntity>(tnae2_id, 3)).ConfigureAwait(false);
			var rev4 = await (AuditReader().FindAsync<TargetNotAuditedEntity>(tnae2_id, 4)).ConfigureAwait(false);

			Assert.AreEqual(uste2, rev1.Reference);
			Assert.AreEqual(uste1, rev2.Reference);
			Assert.AreEqual(uste2, rev3.Reference);
			Assert.AreEqual(uste1, rev4.Reference);
		}
	}
}