//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using NUnit.Framework;

namespace NHibernate.Envers.Tests.Integration.Data
{
	using System.Threading.Tasks;
	public partial class EnumTest : TestBase
	{

		[Test]
		public async Task VerifyRevisionCountAsync()
		{
			CollectionAssert.AreEquivalent(new[] { 1, 2 }, await (AuditReader().GetRevisionsAsync(typeof(EnumTestEntity), id1)).ConfigureAwait(false));
		}

		[Test]
		public async Task VerifyHistoryOfId1Async()
		{
			var ver1 = new EnumTestEntity {Id = id1, Enum1 = E1.X, Enum2 = E2.A};
			var ver2 = new EnumTestEntity {Id = id1, Enum1 = E1.Y, Enum2 = E2.B};

			Assert.AreEqual(ver1, await (AuditReader().FindAsync<EnumTestEntity>(id1, 1)).ConfigureAwait(false));
			Assert.AreEqual(ver2, await (AuditReader().FindAsync<EnumTestEntity>(id1, 2)).ConfigureAwait(false));
		}
	}
}