//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System.Collections.Generic;
using System.Linq;
using NUnit.Framework;
using SharpTestsEx;

namespace NHibernate.Envers.Tests.Integration.EntityNames.ManyToManyAudited
{
	using System.Threading.Tasks;
	using System.Threading;
	public partial class ReadEntityWithAuditedManyToManyTest : TestBase
	{

		private async Task loadDataOnSessionAndAuditReaderAsync(CancellationToken cancellationToken = default(CancellationToken))
		{
			car1_2 = await (AuditReader().FindAsync<Car>(id_car1, 2, cancellationToken)).ConfigureAwait(false);
			var car2_2 = await (AuditReader().FindAsync<Car>(id_car2, 2, cancellationToken)).ConfigureAwait(false);

			// navigate through relations to load objects
			foreach (var foo in from owner in car1_2.Owners from car in owner.Cars select car.Number)
			{
			}
			foreach (var foo in from owner in car2_2.Owners from car in owner.Cars select car.Number)
			{
			}

			car1 = await (Session.GetAsync<Car>(id_car1, cancellationToken)).ConfigureAwait(false);
			person1_1 = (Person) await (AuditReader().FindAsync("Personaje", id_pers1, 1, cancellationToken)).ConfigureAwait(false);
		}

		private async Task checkEntityNamesAsync(CancellationToken cancellationToken = default(CancellationToken))
		{
			AuditReader().GetEntityName(id_pers1, 1, person1_1)
				.Should().Be.EqualTo("Personaje");
			AuditReader().GetEntityName(id_car1, 2, car1_2)
				.Should().Be.EqualTo(await (Session.GetEntityNameAsync(car1, cancellationToken)).ConfigureAwait(false));
		}

		[Test]
		public async Task ShouldGetEntityNameManyToManyWithEntityNameAsync()
		{
			await (loadDataOnSessionAndAuditReaderAsync()).ConfigureAwait(false);
			await (checkEntityNamesAsync()).ConfigureAwait(false);
		}

		[Test]
		public async Task ShouldGetEntityNameManyToManyWithEntityNameInNewSessionAsync()
		{
			ForceNewSession();
			await (loadDataOnSessionAndAuditReaderAsync()).ConfigureAwait(false);
			await (checkEntityNamesAsync()).ConfigureAwait(false);
		}
	}
}