//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System.Collections.Generic;
using NHibernate.Envers.Tests.Entities;
using NUnit.Framework;
using SharpTestsEx;

namespace NHibernate.Envers.Tests.Integration.Merge
{
	using System.Threading.Tasks;
	public partial class AddDelTest : TestBase
	{

		[Test]
		public async Task ShouldNotHaveCreatedRevisionForEntityInRevision2Async()
		{
			(await (AuditReader().GetRevisionsAsync(typeof(GivenIdStrEntity), id)).ConfigureAwait(false))
				.Should().Have.SameSequenceAs(1, 3);
		}

		[Test]
		public async Task ShouldHaveCorrectHistoryAsync()
		{
			(await (AuditReader().FindAsync<GivenIdStrEntity>(id, 1)).ConfigureAwait(false))
				.Should().Be.EqualTo(new GivenIdStrEntity {Id = id, Data = "data"});
			(await (AuditReader().FindAsync<GivenIdStrEntity>(id, 3)).ConfigureAwait(false))
				.Should().Be.EqualTo(new GivenIdStrEntity { Id = id, Data = "modified data" });
		}
	}
}