//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System.Collections.Generic;
using NHibernate.Envers.Tests.Entities.Components;
using NHibernate.Mapping;
using NUnit.Framework;
using SharpTestsEx;

namespace NHibernate.Envers.Tests.Integration.Components
{
	using System.Threading.Tasks;
	public partial class PropertiesGroupTest : TestBase
	{

		[Test]
		public async Task VerifyHistoryOfUniquePropsEntityAsync()
		{
			var expected = new UniquePropsEntity {Id = auditedId, Data1 = "data1", Data2 = "data2"};
			(await (AuditReader().FindAsync<UniquePropsEntity>(auditedId, 1)).ConfigureAwait(false))
				.Should().Be.EqualTo(expected);
		}

		[Test]
		public async Task VerifyHistoryOfUniquePropsNotAuditedEntityAsync()
		{
			var expected = new UniquePropsNotAuditedEntity { Id = notAuditedId, Data1 = "data3"};
			(await (AuditReader().FindAsync<UniquePropsNotAuditedEntity>(notAuditedId, 2)).ConfigureAwait(false))
				.Should().Be.EqualTo(expected);
		}
	}
}