//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using NUnit.Framework;
using SharpTestsEx;

namespace NHibernate.Envers.Tests.NetSpecific.Integration.EnumType
{
	using System.Threading.Tasks;
	public partial class CustomEnumTypeTest : TestBase
	{

		[Test]
		public async Task VerifyRevisionCountAsync()
		{
			(await (AuditReader().GetRevisionsAsync(typeof(Entity), id)).ConfigureAwait(false))
				.Should().Have.SameSequenceAs(1);
		}

		[Test]
		public async Task VerifyHistoryOfEntityAsync()
		{
			(await (AuditReader().FindAsync<Entity>(id, 1)).ConfigureAwait(false)).EntityEnum.Should().Be.EqualTo(EntityEnum.TypeB);
		}
	}
}