//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System.Linq;
using NUnit.Framework;
using SharpTestsEx;

namespace NHibernate.Envers.Tests.NetSpecific.Integration.JoinAuditTable
{
	using System.Threading.Tasks;
	public partial class MultipleJoinAuditTableTest : TestBase
	{

		[Test]
		public async Task VerifyRevisionCountAsync()
		{
			CollectionAssert.AreEquivalent(new[] { 1, 2 }, await (AuditReader().GetRevisionsAsync(typeof(Animal),id)).ConfigureAwait(false));
		}

		[Test]
		public async Task VerifyHistoryOfOwningAsync()
		{
			var ver1 = new Animal { Id = id};
			var ver2 = new Animal { Id = id, Height = 14, Weight = 45};

			(await (AuditReader().FindAsync<Animal>(id, 1)).ConfigureAwait(false))
				.Should().Be.EqualTo(ver1);
			(await (AuditReader().FindAsync<Animal>(id, 2)).ConfigureAwait(false))
				.Should().Be.EqualTo(ver2);
		}

	}
}