//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System.Collections.Generic;
using NHibernate.Envers.Tests.Integration.Basic;
using NHibernate.Envers.Tests.Tools;
using NUnit.Framework;
using SharpTestsEx;

namespace NHibernate.Envers.Tests.Integration.ModifiedFlags
{
	using System.Threading.Tasks;
	public partial class HasChangedUnversionedPropertiesTest : AbstractModifiedFlagsEntityTest
	{

		[Test]
		public async Task VerifyHasChangedQueryAsync()
		{
			(await (QueryForPropertyHasChangedAsync(typeof (BasicTestEntity2), id, "Str1")).ConfigureAwait(false))
				.ExtractRevisionNumbersFromRevision()
				.Should().Have.SameSequenceAs(1, 2);
		}

		[Test]
		public void ShouldThrowExceptionOnHasChangedQueryAsync()
		{
			Assert.ThrowsAsync<QueryException>(() =>
			         QueryForPropertyHasChangedWithDeletedAsync(typeof (BasicTestEntity2), id, "Str2"));
		}
	}
}