//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System.Collections.Generic;
using NHibernate.Envers.Tests.Integration.ModifiedFlags.Entities.ManyToMany;
using NUnit.Framework;
using SharpTestsEx;

namespace NHibernate.Envers.Tests.Integration.ModifiedFlags
{
	using System.Threading.Tasks;
	public partial class HasChangedAuditedManyToManyRemovalTest : AbstractModifiedFlagsEntityTest
	{

		[Test]
		public async Task ShouldNotThrowAsync()
		{
			(await (AuditReader().GetRevisionsAsync(typeof(Professor), professorId)).ConfigureAwait(false)).Should().Have.SameSequenceAs(1, 2);
			(await (AuditReader().GetRevisionsAsync(typeof(Student), studentId)).ConfigureAwait(false)).Should().Have.SameSequenceAs(1, 2);
		}
	}
}