//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System.Collections.Generic;
using NHibernate.Envers.Tests.Integration.Inheritance.Entities;
using NHibernate.Envers.Tests.Tools;
using NUnit.Framework;
using SharpTestsEx;

namespace NHibernate.Envers.Tests.Integration.ModifiedFlags
{
	using System.Threading.Tasks;
	public partial class HasChangedNotOwnedBidirectionalTest : AbstractModifiedFlagsEntityTest
	{

		[Test]
		public async Task VerifyReferencedEntityHasChangedAsync()
		{
			(await (QueryForPropertyHasChangedAsync(typeof (PersonalContact), pc_id, "Addresses")).ConfigureAwait(false))
				.ExtractRevisionNumbersFromRevision()
				.Should().Have.SameSequenceAs(1, 2);
			(await (QueryForPropertyHasChangedAsync(typeof(Address), a1_id, "Contact")).ConfigureAwait(false))
				.ExtractRevisionNumbersFromRevision()
				.Should().Have.SameSequenceAs(1);
			(await (QueryForPropertyHasChangedAsync(typeof(Address), a2_id, "Contact")).ConfigureAwait(false))
				.ExtractRevisionNumbersFromRevision()
				.Should().Have.SameSequenceAs(2);

		}
	}
}