//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System.Collections.Generic;
using NHibernate.Envers.Tests.Integration.Inheritance.Entities;
using NHibernate.Envers.Tests.Tools;
using NUnit.Framework;
using SharpTestsEx;

namespace NHibernate.Envers.Tests.Integration.ModifiedFlags
{
	using System.Threading.Tasks;
	public partial class HasChangedChildAuditingTest : AbstractModifiedFlagsEntityTest
	{

		[Test]
		public async Task VerifyChildHasChangedAsync()
		{
			(await (QueryForPropertyHasChangedAsync(typeof(ChildEntity), id, "Data")).ConfigureAwait(false))
				.ExtractRevisionNumbersFromRevision().Should().Have.SameSequenceAs(1, 2);
			(await (QueryForPropertyHasChangedAsync(typeof(ChildEntity), id, "Number")).ConfigureAwait(false))
				.ExtractRevisionNumbersFromRevision().Should().Have.SameSequenceAs(1, 2);
			(await (QueryForPropertyHasNotChangedAsync(typeof(ChildEntity), id, "Data")).ConfigureAwait(false))
				.ExtractRevisionNumbersFromRevision().Should().Be.Empty();
			(await (QueryForPropertyHasNotChangedAsync(typeof(ChildEntity), id, "Number")).ConfigureAwait(false))
				.ExtractRevisionNumbersFromRevision().Should().Be.Empty();
		}

		[Test]
		public async Task VerifyParentHasChangedAsync()
		{
			(await (QueryForPropertyHasChangedAsync(typeof(ParentEntity), id, "Data")).ConfigureAwait(false))
				.ExtractRevisionNumbersFromRevision().Should().Have.SameSequenceAs(1, 2);
			(await (QueryForPropertyHasNotChangedAsync(typeof(ParentEntity), id, "Data")).ConfigureAwait(false))
				.ExtractRevisionNumbersFromRevision().Should().Be.Empty();
		}
	}
}