//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System.Collections.Generic;
using NHibernate.Envers.Tests.Integration.Basic;
using NUnit.Framework;
using SharpTestsEx;

namespace NHibernate.Envers.Tests.Integration.ModifiedFlags
{
	using System.Threading.Tasks;
	public partial class HasChangedInsertUpdateSameTransactionTest : AbstractModifiedFlagsEntityTest
	{

		[Test]
		public async Task VerifyPropertyChangedInsertUpdateSameTransactionAsync()
		{
			(await (QueryForPropertyHasChangedAsync(typeof(BasicTestEntity1), 1, "Long1")).ConfigureAwait(false)).Count
				.Should().Be.EqualTo(1);
		}
	}
}