//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System.Collections.Generic;
using NUnit.Framework;

namespace NHibernate.Envers.Tests.Integration.Naming
{
	using System.Threading.Tasks;
	public partial class BasicNamingTest : TestBase
	{

		[Test]
		public async Task VerifyRevisionCountAsync()
		{
			CollectionAssert.AreEquivalent(new[] { 1, 2 }, await (AuditReader().GetRevisionsAsync(typeof(NamingTestEntity1), id1)).ConfigureAwait(false));
			CollectionAssert.AreEquivalent(new[] { 1, 3 }, await (AuditReader().GetRevisionsAsync(typeof(NamingTestEntity1), id2)).ConfigureAwait(false));
		}

		[Test]
		public async Task VerifyHistoryOfId1Async()
		{
			var ver1 = new NamingTestEntity1 {Id = id1, Data = "data1"};
			var ver2 = new NamingTestEntity1 {Id = id1, Data = "data1'"};

			Assert.AreEqual(ver1, await (AuditReader().FindAsync<NamingTestEntity1>(id1, 1)).ConfigureAwait(false));
			Assert.AreEqual(ver2, await (AuditReader().FindAsync<NamingTestEntity1>(id1, 2)).ConfigureAwait(false));
			Assert.AreEqual(ver2, await (AuditReader().FindAsync<NamingTestEntity1>(id1, 3)).ConfigureAwait(false));
		}

		[Test]
		public async Task VerifyHistoryOfId2Async()
		{
			var ver1 = new NamingTestEntity1 { Id = id2, Data = "data2" };
			var ver2 = new NamingTestEntity1 { Id = id2, Data = "data2'" };

			Assert.AreEqual(ver1, await (AuditReader().FindAsync<NamingTestEntity1>(id2, 1)).ConfigureAwait(false));
			Assert.AreEqual(ver1, await (AuditReader().FindAsync<NamingTestEntity1>(id2, 2)).ConfigureAwait(false));
			Assert.AreEqual(ver2, await (AuditReader().FindAsync<NamingTestEntity1>(id2, 3)).ConfigureAwait(false));
		}
	}
}