//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System.Collections.Generic;
using ee.Estonia.Entities;
using NHibernate.Envers.Configuration.Attributes;
using NUnit.Framework;
using SharpTestsEx;

namespace NHibernate.Envers.Tests.Integration.Naming
{
	using System.Threading.Tasks;
	public partial class EstonianTableAliasTest : TestBase
	{

		[Test]
		public async Task VerifyAuditChildTableAliasAsync()
		{
			var parent = new Parent { Data = "data", Id = parentId };
			var child = new Child { Data = "child", Id = childId };

			var ver1 = await (AuditReader().FindAsync<Parent>(parentId, 1)).ConfigureAwait(false);

			ver1.Should().Be.EqualTo(parent);
			ver1.Collection.Should().Have.SameValuesAs(child);
		}
	}
}
