//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using NHibernate.Cfg;
using NHibernate.Envers.Configuration;
using NUnit.Framework;
using SharpTestsEx;

namespace NHibernate.Envers.Tests.Integration.Properties
{
	using System.Threading.Tasks;
	public partial class VersionsPropertiesTest : TestBase
	{

		[Test]
		public async Task VerifyRevisionCountsAsync()
		{
			(await (AuditReader().GetRevisionsAsync(typeof(PropertiesTestEntity), id)).ConfigureAwait(false))
				.Should().Have.SameSequenceAs(1, 2);
		}

		[Test]
		public async Task VerifyHistoryAsync()
		{
			var ver1 = new PropertiesTestEntity { Id = id, Str = "x" };
			var ver2 = new PropertiesTestEntity { Id = id, Str = "y" };

			(await (AuditReader().FindAsync<PropertiesTestEntity>(id, 1)).ConfigureAwait(false))
				.Should().Be.EqualTo(ver1);
			(await (AuditReader().FindAsync<PropertiesTestEntity>(id, 2)).ConfigureAwait(false))
				.Should().Be.EqualTo(ver2);
		}
	}
}