//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System.Collections.Generic;
using NHibernate.Envers.Tests.Entities.OneToMany;
using NUnit.Framework;

namespace NHibernate.Envers.Tests.Integration.OneToMany
{
	using System.Threading.Tasks;
	public partial class BasicSetWithNullsDeleteTest : TestBase
	{

		[Test]
		public async Task VerifyRevisionCountAsync()
		{
			CollectionAssert.AreEquivalent(new[] { 1, 2, 3, 4, 5 }, await (AuditReader().GetRevisionsAsync(typeof(SetRefEdEntity), ed1_id)).ConfigureAwait(false));
			CollectionAssert.AreEquivalent(new[] { 1, 4 }, await (AuditReader().GetRevisionsAsync(typeof(SetRefEdEntity), ed2_id)).ConfigureAwait(false));

			CollectionAssert.AreEquivalent(new[] { 1, 2 }, await (AuditReader().GetRevisionsAsync(typeof(SetRefIngEntity), ing1_id)).ConfigureAwait(false));
			CollectionAssert.AreEquivalent(new[] { 1, 3 }, await (AuditReader().GetRevisionsAsync(typeof(SetRefIngEntity), ing2_id)).ConfigureAwait(false));
			CollectionAssert.AreEquivalent(new[] { 1, 4 }, await (AuditReader().GetRevisionsAsync(typeof(SetRefIngEntity), ing3_id)).ConfigureAwait(false));
			CollectionAssert.AreEquivalent(new[] { 1, 5 }, await (AuditReader().GetRevisionsAsync(typeof(SetRefIngEntity), ing4_id)).ConfigureAwait(false));
		}

		[Test]
		public async Task VerifyHistoryOfEd1Async()
		{
			var ing1 = await (Session.GetAsync<SetRefIngEntity>(ing1_id)).ConfigureAwait(false);
			var ing2 = new SetRefIngEntity {Id = ing2_id, Data = "data_ing_2"};
			var ing3 = await (Session.GetAsync<SetRefIngEntity>(ing3_id)).ConfigureAwait(false);
			var ing4 = await (Session.GetAsync<SetRefIngEntity>(ing4_id)).ConfigureAwait(false);

			var rev1 = await (AuditReader().FindAsync<SetRefEdEntity>(ed1_id, 1)).ConfigureAwait(false);
			var rev2 = await (AuditReader().FindAsync<SetRefEdEntity>(ed1_id, 2)).ConfigureAwait(false);
			var rev3 = await (AuditReader().FindAsync<SetRefEdEntity>(ed1_id, 3)).ConfigureAwait(false);
			var rev4 = await (AuditReader().FindAsync<SetRefEdEntity>(ed1_id, 4)).ConfigureAwait(false);
			var rev5 = await (AuditReader().FindAsync<SetRefEdEntity>(ed1_id, 5)).ConfigureAwait(false);

			CollectionAssert.AreEquivalent(new[] { ing1, ing2, ing3, ing4 }, rev1.Reffering);
			CollectionAssert.AreEquivalent(new[] { ing2, ing3, ing4 }, rev2.Reffering);
			CollectionAssert.AreEquivalent(new[] { ing3, ing4 }, rev3.Reffering);
			CollectionAssert.AreEquivalent(new[] { ing4 }, rev4.Reffering);
			Assert.IsNull(rev5);
		}

		[Test]
		public async Task VerifyHistoryOfEd2Async()
		{
			var ing3 = await (Session.GetAsync<SetRefIngEntity>(ing3_id)).ConfigureAwait(false);

			var rev1 = await (AuditReader().FindAsync<SetRefEdEntity>(ed2_id, 1)).ConfigureAwait(false);
			var rev2 = await (AuditReader().FindAsync<SetRefEdEntity>(ed2_id, 2)).ConfigureAwait(false);
			var rev3 = await (AuditReader().FindAsync<SetRefEdEntity>(ed2_id, 3)).ConfigureAwait(false);
			var rev4 = await (AuditReader().FindAsync<SetRefEdEntity>(ed2_id, 4)).ConfigureAwait(false);
			var rev5 = await (AuditReader().FindAsync<SetRefEdEntity>(ed2_id, 5)).ConfigureAwait(false);

			CollectionAssert.IsEmpty(rev1.Reffering);
			CollectionAssert.IsEmpty(rev2.Reffering);
			CollectionAssert.IsEmpty(rev3.Reffering);
			CollectionAssert.AreEquivalent(new[] { ing3 }, rev4.Reffering);
			CollectionAssert.AreEquivalent(new[] { ing3 }, rev5.Reffering);
		}

		[Test]
		public async Task VerifyHistoryOfIng1Async()
		{
			var ed1 = new SetRefEdEntity {Id = ed1_id, Data = "data_ed_1"};

			var rev1 = await (AuditReader().FindAsync<SetRefIngEntity>(ing1_id, 1)).ConfigureAwait(false);
			var rev2 = await (AuditReader().FindAsync<SetRefIngEntity>(ing1_id, 2)).ConfigureAwait(false);
			var rev3 = await (AuditReader().FindAsync<SetRefIngEntity>(ing1_id, 3)).ConfigureAwait(false);
			var rev4 = await (AuditReader().FindAsync<SetRefIngEntity>(ing1_id, 4)).ConfigureAwait(false);
			var rev5= await (AuditReader().FindAsync<SetRefIngEntity>(ing1_id, 5)).ConfigureAwait(false);

			Assert.AreEqual(ed1, rev1.Reference);
			Assert.IsNull(rev2.Reference);
			Assert.IsNull(rev3.Reference);
			Assert.IsNull(rev4.Reference);
			Assert.IsNull(rev5.Reference);
		}

		[Test]
		public async Task VerifyHistoryOfIng2Async()
		{
			var ed1 = new SetRefEdEntity { Id = ed1_id, Data = "data_ed_1" };

			var rev1 = await (AuditReader().FindAsync<SetRefIngEntity>(ing2_id, 1)).ConfigureAwait(false);
			var rev2 = await (AuditReader().FindAsync<SetRefIngEntity>(ing2_id, 2)).ConfigureAwait(false);
			var rev3 = await (AuditReader().FindAsync<SetRefIngEntity>(ing2_id, 3)).ConfigureAwait(false);
			var rev4 = await (AuditReader().FindAsync<SetRefIngEntity>(ing2_id, 4)).ConfigureAwait(false);
			var rev5 = await (AuditReader().FindAsync<SetRefIngEntity>(ing2_id, 5)).ConfigureAwait(false);

			Assert.AreEqual(ed1, rev1.Reference);
			Assert.AreEqual(ed1, rev2.Reference);
			Assert.IsNull(rev3);
			Assert.IsNull(rev4);
			Assert.IsNull(rev5);
		}

		[Test]
		public async Task VerifyHistoryOfIng3Async()
		{
			var ed1 = new SetRefEdEntity { Id = ed1_id, Data = "data_ed_1" };
			var ed2 = new SetRefEdEntity { Id = ed2_id, Data = "data_ed_2" };

			var rev1 = await (AuditReader().FindAsync<SetRefIngEntity>(ing3_id, 1)).ConfigureAwait(false);
			var rev2 = await (AuditReader().FindAsync<SetRefIngEntity>(ing3_id, 2)).ConfigureAwait(false);
			var rev3 = await (AuditReader().FindAsync<SetRefIngEntity>(ing3_id, 3)).ConfigureAwait(false);
			var rev4 = await (AuditReader().FindAsync<SetRefIngEntity>(ing3_id, 4)).ConfigureAwait(false);
			var rev5 = await (AuditReader().FindAsync<SetRefIngEntity>(ing3_id, 5)).ConfigureAwait(false);

			Assert.AreEqual(ed1, rev1.Reference);
			Assert.AreEqual(ed1, rev2.Reference);
			Assert.AreEqual(ed1, rev3.Reference);
			Assert.AreEqual(ed2, rev4.Reference);
			Assert.AreEqual(ed2, rev5.Reference);
		}

		[Test]
		public async Task VerifyHistoryOfIng4Async()
		{
			var ed1 = new SetRefEdEntity { Id = ed1_id, Data = "data_ed_1" };

			var rev1 = await (AuditReader().FindAsync<SetRefIngEntity>(ing4_id, 1)).ConfigureAwait(false);
			var rev2 = await (AuditReader().FindAsync<SetRefIngEntity>(ing4_id, 2)).ConfigureAwait(false);
			var rev3 = await (AuditReader().FindAsync<SetRefIngEntity>(ing4_id, 3)).ConfigureAwait(false);
			var rev4 = await (AuditReader().FindAsync<SetRefIngEntity>(ing4_id, 4)).ConfigureAwait(false);
			var rev5 = await (AuditReader().FindAsync<SetRefIngEntity>(ing4_id, 5)).ConfigureAwait(false);

			Assert.AreEqual(ed1, rev1.Reference);
			Assert.AreEqual(ed1, rev2.Reference);
			Assert.AreEqual(ed1, rev3.Reference);
			Assert.AreEqual(ed1, rev4.Reference);
			Assert.IsNull(rev5.Reference);
		}
	}
}