//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System.Collections;
using System.Collections.Generic;
using NHibernate.Cfg;
using NHibernate.Envers.Configuration;
using NHibernate.Envers.Query;
using NHibernate.Envers.Tests.Entities;
using NUnit.Framework;

namespace NHibernate.Envers.Tests.Integration.Query
{
	using System.Threading.Tasks;
	public partial class StoreDeletedDataTest : TestBase
	{

		[Test]
		public async Task VerifyRevisionsPropertyEqQueryAsync()
		{
			var revsId1 = await (AuditReader().CreateQuery()
							.ForRevisionsOfEntity(typeof (StrIntTestEntity), false, true)
							.Add(AuditEntity.Id().Eq(id1))
							.GetResultListAsync<IList>()).ConfigureAwait(false);
			Assert.AreEqual(2, revsId1.Count);
			Assert.AreEqual(new StrIntTestEntity { Str = "a", Number = 10, Id=id1 }, revsId1[0][0]);
			Assert.AreEqual(new StrIntTestEntity { Str = "a", Number = 10, Id = id1 }, revsId1[1][0]);
		}
	}
}