//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Collections.Generic;
using NHibernate.Envers.Tests.Entities.Ids;
using NUnit.Framework;
using SharpTestsEx;

namespace NHibernate.Envers.Tests.Integration.Ids
{
	using System.Threading.Tasks;
	public partial class CompositeDateIdTest : TestBase
	{


		[Test]
		public async Task VerifyRevisionCountAsync()
		{
			(await (AuditReader().GetRevisionsAsync(typeof (CompositeDateIdTestEntity), id)).ConfigureAwait(false))
				.Should().Have.SameSequenceAs(1, 2);
		}

		[Test]
		public async Task VerifyHistoryAsync()
		{
			(await (AuditReader().FindAsync<CompositeDateIdTestEntity>(id, 1)).ConfigureAwait(false)).Str1
				.Should().Be.EqualTo("x");
			(await (AuditReader().FindAsync<CompositeDateIdTestEntity>(id, 2)).ConfigureAwait(false)).Str1
				.Should().Be.EqualTo("y");
		}

	}
}