//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using NUnit.Framework;

namespace NHibernate.Envers.Tests.Integration.Basic
{
	using System.Threading.Tasks;
	public partial class GlobalVersionedTest : TestBase
	{

		[Test]
		public async Task VerifyRevisionCountAsync()
		{
			CollectionAssert.AreEquivalent(new[] { 1, 2 }, await (AuditReader().GetRevisionsAsync(typeof(BasicTestEntity4), id1)).ConfigureAwait(false));
		}

		[Test]
		public async Task VerifyHistoryAsync()
		{
			var ver1 = new BasicTestEntity4 { Id = id1, Str1 = "x", Str2 = "y" };
			var ver2 = new BasicTestEntity4 { Id = id1, Str1 = "a", Str2 = "b" };

			Assert.AreEqual(ver1, await (AuditReader().FindAsync<BasicTestEntity4>(id1, 1)).ConfigureAwait(false));
			Assert.AreEqual(ver2, await (AuditReader().FindAsync<BasicTestEntity4>(id1, 2)).ConfigureAwait(false));
		}
	}
}