//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using NHibernate.Envers.Exceptions;
using NUnit.Framework;

namespace NHibernate.Envers.Tests.Integration.Basic
{
	using System.Threading.Tasks;
	public partial class NonVersionedTest : TestBase
	{

		[Test]
		public void VerifyRevisionCountAsync()
		{
			Assert.ThrowsAsync<NotAuditedException>(() =>
				AuditReader().GetRevisionsAsync(typeof(BasicTestEntity3),id1)
			);
		}

		[Test]
		public void VerifyHistoryAsync()
		{
			Assert.ThrowsAsync<NotAuditedException>(() =>
				AuditReader().FindAsync<BasicTestEntity3>(id1, 1)
			);
		}
	}
}