//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using NUnit.Framework;

namespace NHibernate.Envers.Tests.Integration.Basic
{
	using System.Threading.Tasks;
	public partial class UnversionedPropertiesChangeTest : TestBase
	{

		[Test]
		public async Task VerifyRevisionCountsAsync()
		{
			CollectionAssert.AreEquivalent(new[] { 1, 2 }, await (AuditReader().GetRevisionsAsync(typeof(BasicTestEntity2), id1)).ConfigureAwait(false));
		}

		[Test]
		public async Task VerifyHistoryOf1Async()
		{
			var ver1 = new BasicTestEntity2 { Id = id1, Str1 = "x"};
			var ver2 = new BasicTestEntity2 { Id = id1, Str1 = "y"};

			Assert.AreEqual(ver1, await (AuditReader().FindAsync<BasicTestEntity2>(id1, 1)).ConfigureAwait(false));
			Assert.AreEqual(ver2, await (AuditReader().FindAsync<BasicTestEntity2>(id1, 2)).ConfigureAwait(false));
		}
	}
}