//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System.Collections.Generic;
using NHibernate.Envers.Tests.Entities;
using NUnit.Framework;

namespace NHibernate.Envers.Tests.Integration.Basic
{
	using System.Threading.Tasks;
	public partial class UnversionedPropertyTest : TestBase
	{

		[Test]
		public async Task VerifyRevisionCountsAsync()
		{
			CollectionAssert.AreEquivalent(new[] { 1, 2}, await (AuditReader().GetRevisionsAsync(typeof(UnversionedEntity), id1)).ConfigureAwait(false));
		}

		[Test]
		public async Task VerifyHistoryOf1Async()
		{
			var ver1 = new UnversionedEntity { Id = id1, Str1 = "a1" };
			var ver2 = new UnversionedEntity { Id = id1, Str1 = "a2" };

			Assert.AreEqual(ver1, await (AuditReader().FindAsync<UnversionedEntity>(id1, 1)).ConfigureAwait(false));
			Assert.AreEqual(ver2, await (AuditReader().FindAsync<UnversionedEntity>(id1, 2)).ConfigureAwait(false));
		}
	}
}